import type { Metadata } from "next"

import "./globals.css"
import { Toaster } from "sonner"
import { ThemeProvider } from "next-themes"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="pt-BR" suppressHydrationWarning>
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                    <Toaster
                        richColors
                        position="bottom-left"
                        data-testid="toster-info"
                    />
                </ThemeProvider>
            </body>
        </html>
    )
}
